version: "3.9"

services:

  postgres:
    container_name: lhv-test-postgres15
    image: postgres:15.5-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ../target/postgresql:/var/lib/postgresql/data
    restart: on-failure:3
    stop_signal: SIGINT
    stop_grace_period: 30s
    mem_limit: 1g
    mem_reservation: 128m